### ISSUE TITLE
Docker image exposes nginx server version for VODAN in a box 

### ISSUE THREAD

**Issue by mpvillerius** [VODAN-Tech/vodan-deployment-production#1]
test :
$ curl -I https://<fdp url>
HTTP/1.1 200 
Server: nginx/1.17.10                              <======================
Date: Mon, 19 Apr 2021 07:25:49 GMT
Content-Type: text/turtle
Content-Length: 2818
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Origin,Authorization,Accept,Content-Type
Access-Control-Expose-Headers: Location
Allow: GET,POST,PUT,PATCH,DELETE
Access-Control-Allow-Methods: GET,POST,PUT,PATCH,DELETE
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY

**Comment by mpvillerius** [comment]
issue can be resolved by adding : server_tokens off;
to the configuration files in proxy/nginx
agraph.conf  dsw.conf  fdp.conf

**Comment by mpvillerius** [comment]
add  server_tokens off;

**Comment by kburger** [comment]
I've added #2 for a proposed solution. `server_tokens` is allowed on [`http, server, location`](https://nginx.org/en/docs/http/ngx_http_core_module.html#server_tokens). Adding it to `server` provide a single line solution, since this is probably desired behaviour for the entire proxy.
